### Matematícas Avanzadas para la Ciencia de Datos
Por Michael Adolfo Huerta Ramírez

#### Metodo Simplex

Para resolver un problema de programación lineal, debemos seguir los siguientes pasos:

- Elegir las incógnitas o variables de decisión.

- Escribir la función objetivo en función de los datos del problema.

- Escribir las restricciones en forma de sistema de inecuaciones.

- Averiguar el conjunto de soluciones factibles representando gráficamente las restricciones.

- Calcular las coordenadas de los vértices del recinto de soluciones factibles (si son pocos).

- Calcular el valor de la función objetivo en cada uno de los vértices para ver en cuál de ellos presenta el valor máximo o mínimo según nos pida el problema (hay que tener en cuenta aquí la posible no existencia de solución).

In [1]:
import numpy as np 
#Crearemos un arreglo donde el primer valor sera Z con relacion que quede de la forma
 # z = 10X_1 + 20X_2
Funcion_a_maximizar = []

#variable de paro
x = True
contador = 0
informacion_paso = "z"

while(x == True):
    if(contador != 0):
        informacion_paso = "X_" + str(contador)
        
            
    variable_entrada = input('Introduce el valor ' + informacion_paso +' de la funcion dada, presiona (X) si terminaste')
    contador +=1
    if(variable_entrada.lower() == 'x'):
        x = False
    else:
         Funcion_a_maximizar.append(int(variable_entrada))
   

print("Funcion a Maximizar")
print(Funcion_a_maximizar)



Funcion a Maximizar
[1, 1, 3]


In [2]:
#Crearemos las restricciones para este sistema
#Estara limitado hasta un máximo de 5 restricciones

#primero para 3 restricciones
def restriccion():
    restriccion = []
    #variable de paro
    x = True
    contador = 1
    informacion_paso = ""

    while(x == True):
        
        informacion_paso = "X_" + str(contador)

        print("Escribe 0 si quieres que la variable este vacia")
        variable_entrada = input('Introduce el valor ' + informacion_paso +' de la funcion dada, presiona (X) si terminaste')
        contador +=1
        if(variable_entrada.lower() == 'x'):
            x = False
        else:
             restriccion.append(int(variable_entrada))

    desigualdad = input('Escribe el valor de la desigualdad')
    restriccion.append(int(desigualdad))
    
    print("Valor de la restriccion")
    print(restriccion)
    return restriccion

Registro de restricciones

In [ ]:
#Total de restricciones
print("Introduce la primera restriccion")
restriccion_1 = restriccion()
print("Introduce la segunda restriccion")
restriccion_2 = restriccion()
print("Introduce la tercera restriccion")
restriccion_3 = restriccion()

In [2]:
#Usamos estos valores para la muestra
restriccion_1 = [-1,1,4]
restriccion_2 = [-1,2,12]
restriccion_3 = [1,1,10]

Validador de restricciones

In [4]:
if(len(restriccion_1) == len(restriccion_2) and len(restriccion_2) == len(restriccion_3)):
    print("Las longitudes de las restricciones son correctas, continuemos: ")
else:
    print("Selecciona diferentes restricciones")

Las longitudes de las restricciones son correctas, continuemos: 


Creacion de la tabla $SIMPLEX$

| Variables Basicas | Z | $$X_1$$ | $$X_2$$ | C.R
| --- | --- | --- | --- | --- |
| $$S_1$$  | 0 | -1 | 1 | 4 |
| $$S_2$$  | 0 | -1 | 2 | 12 |
| $$S_3$$  | 0 | 1 | 1 | 10 |
| $$Z$$    | 1 | -1 | -3 | 0 |

In [3]:
#zNegativa  es la primera funcion , la Funcion_a_maximizar en valores negativos donde

# Z -20X_1 -10X_2

F_a_M_Transformada = []

for x in range(len(Funcion_a_maximizar)):
    valores = 0
    if(x == 0):
        valores = int(Funcion_a_maximizar[x])
    else:
        valores = int(Funcion_a_maximizar[x])*-1
    F_a_M_Transformada.append(valores)
    
print("Valor de la funcion Z transformada: ")    
print(F_a_M_Transformada)
    
min_value = min(F_a_M_Transformada)
print('Valor Minimo:', min_value, "En el indice:", F_a_M_Transformada.index(min_value))  
    

Valor de la funcion Z transformada: 
[1, -1, -3]
Valor Minimo: -3 En el indice: 2


Despúes agregaremos las variables pivotes

| Variables Basicas | Z | $$X_1$$ | $$X_2$$ | $$S_1$$| $$S_2$$ | $$S_2$$ | C.R
| --- | --- | --- | --- | --- | --- | --- | --- |
| $$S_1$$  | 0 | -1 | 1 | 1 | 0 |  0 | 4
| $$S_2$$  | 0 | -1 | 2 | 0 | 1 | 0  | 12
| $$S_3$$  | 0 | 1| 1 | 0 | 0 | 1  | 10
| $$Z$$    | 1 | -1 | -3 | 0 | 0 | 0 | 0

In [4]:
#asignamos las restricciones a variables s , para despues agregar las variables pivote
s1 = (restriccion_1)
s2 = (restriccion_2)
s3 = (restriccion_3)

#seleccionamos el ultimo elemento
s1_utlimo = (s1[-1])
s2_utlimo = (s2[-1])
s3_utlimo = (s3[-1])

#quitamos por mientras el ultimo valor
s1.pop()
s2.pop()
s3.pop()

#creamos las listas pivote
pivote_1 = [1,0,0]
pivote_2 = [0,1,0]
pivote_3 = [0,0,1]
pivote_4 = [0,0,0,0]
#añadimos los valores 0 al inicio de cada lista s    
s1 = [0, *s1]
s2 = [0, *s2]
s3 = [0, *s3]
    
    
#observamos como van las listas
print(s1)
print(s2)
print(s3)

#s1 = []
#s2 = []
#s3 = []

#añadir valores pivote

s1.extend(pivote_1)
s2.extend(pivote_2)
s3.extend(pivote_3)
F_a_M_Transformada.extend(pivote_4)

#añadir ultimo valor
s1.append(s1_utlimo)
s2.append(s2_utlimo)
s3.append(s3_utlimo)

#creamos un arreglo que despues volveremos a usar
ss1 = np.array(s1)
ss2 = np.array(s2)
ss3 = np.array(s3)
print(ss1)

[0, -1, 1]
[0, -1, 2]
[0, 1, 1]
[ 0 -1  1  1  0  0  4]


In [7]:
# metodo para limpiar las listas
#s1.clear()
#s2.clear()
#s3.clear()


In [5]:
#metodo para agregar todas las listas dentro de una para luego transformarla en matriz
lista_general = s1.extend(s2)
lista_general = s1.extend(s3)


In [6]:
#agregamos la columna z
lista_general = s1.extend(F_a_M_Transformada)

In [7]:
lista_matriz = []
lista_matriz = s1
print(lista_matriz)

[0, -1, 1, 1, 0, 0, 4, 0, -1, 2, 0, 1, 0, 12, 0, 1, 1, 0, 0, 1, 10, 1, -1, -3, 0, 0, 0, 0]


In [8]:

x = np.array(lista_matriz).reshape(4,7)
print(x)

[[ 0 -1  1  1  0  0  4]
 [ 0 -1  2  0  1  0 12]
 [ 0  1  1  0  0  1 10]
 [ 1 -1 -3  0  0  0  0]]


Nota: El objetivo es encontrar la columna pivote que tenga el valor más negativo en la funcion $Z$ para optener el valor óptimo

En este caso como vimos arriba se encontro la columna $X_2$
<br></br>

|$$X_2$$|
|---|
|1|
|2|
|1|
|-3|

Ahora se divide el elemento $CR$ entre el elemento pivote que le corresponde:
<br>
$Z$ no se divide debido a que siempre es $0$


$\frac{4}{1} = 4$
<br>

$\frac{12}{2} = 6$
<br>

$\frac{10}{1} = 10$

In [9]:
import pandas as pd

#Podemos visualizarlo de mejor manera con un daframe en pandas

df = pd.DataFrame(data=x )
df

0  1  2  3  4  5   6
0  0 -1  1  1  0  0   4
1  0 -1  2  0  1  0  12
2  0  1  1  0  0  1  10
3  1 -1 -3  0  0  0   0

Recordemos que el menor valor de z estaba en la posicion de indice 2 , por lo cual usaremos esa lista para dividir

In [10]:
#resultado operacion =>

fila_a_dividir = df[2]
valor_minimo_iteracion_1 = []

for x in range(len(fila_a_dividir)-1):
    print(df[6][x]/fila_a_dividir[x])
    valor_minimo_iteracion_1.append(df[6][x]/fila_a_dividir[x])
    
#eliminamos valor z 
min_value_i = min(valor_minimo_iteracion_1)    
print('Valor Minimo:', min_value_i, "En el indice:", F_a_M_Transformada.index(min_value)) 
    

4.0
6.0
10.0
Valor Minimo: 4.0 En el indice: 2


El valor 2 es el número 8 , posicionado en la fila 1 columna 2

| Variables Basicas | Z | $$X_1$$ | $$X_2$$ | $$S_1$$| $$S_2$$ | $$S_3$$ | C.R
| --- | --- | --- | --- | --- | --- | --- | --- |
| $$S_1$$  | 0 | -1 | 1 | 1 | 0 |  0 | 4
| $$X_2$$  | 0/1 | -1/1 | 2/1 | 0/1 | 1/1 | 0/1  | 12/1
| $$S_3$$  | 0 | 1 | 1 | 0 | 0 | 1  | 10
| $$Z$$    | 1 | -1 | -3 | 0 | 0 | 0 | 0

In [11]:
#division de fila x_2 entre 8 que es el valor pivote
FE = []
for v in range(len(ss2)):
    division = ss2[v] / 1
    FE.append(division)
print(FE)

[0.0, -1.0, 2.0, 0.0, 1.0, 0.0, 12.0]


Ahora crearemos las nuevas tablas con la funcion:
<br>
Fila Vieja $S_n - (CPFVS_n * F.E)$ 
<br>
Por ejemplo:

In [12]:
#sabemos que el indice dos es donde vamos a seleccionar el valor pivote, dentro de la fila S_1
# el valor de X_2 es = 2 entonces vamos a crear un arreglo con ese valor para ejecutar la operacion

#Fila Vieja S_1
print(ss1)
CPVFS_1 = []
for u in range(len(ss1)):
    CPVFS_1.append(1)
print(CPVFS_1)    

[ 0 -1  1  1  0  0  4]
[1, 1, 1, 1, 1, 1, 1]


In [18]:
#Una vez que ya tenemos todas nuestras variables podemos empezar a operarlas ss1 - (CPVFS_1*F.E)

In [13]:
fila_nuevaS1 = []
for f in range(len(ss1)):
    operacion = ss1[f] - (CPVFS_1[f]*FE[f])
    fila_nuevaS1.append(operacion)
print(fila_nuevaS1)    

[0.0, 0.0, -1.0, 1.0, -1.0, 0.0, -8.0]


In [21]:
#Ahora que ya tenemos la nueva fila S1 operaremos para S3 bajo el mismo fundamento para asi obtener los valores 

In [14]:
#sabemos que el indice dos es donde vamos a seleccionar el valor pivote, dentro de la fila S_3
# el valor de X_2 es = 2 entonces vamos a crear un arreglo con ese valor para ejecutar la operacion

#Fila Vieja S_3
print(ss3)
CPVFS_3 = []
for u in range(len(ss3)):
    CPVFS_3.append(1)
print(CPVFS_3)  

fila_nuevaS3 = []
for f in range(len(ss3)):
    operacion = ss3[f] - (CPVFS_3[f]*FE[f])
    fila_nuevaS3.append(operacion)
print(fila_nuevaS3)    

[ 0  1  1  0  0  1 10]
[1, 1, 1, 1, 1, 1, 1]
[0.0, 2.0, -1.0, 0.0, -1.0, 1.0, -2.0]


Por ultimo haremos esto para el valor Z  recordemos que el valor pivote en dentro de la fila z corresponde a $-20$

In [15]:
#Fila Vieja Z
zs = np.array(F_a_M_Transformada)
print(zs)
CPVFz = []
for u in range(len(zs)):
    CPVFz.append(-3)
print(CPVFz)  

fila_nuevaz = []
for f in range(len(zs)):
    operacion = zs[f] - (CPVFz[f]*FE[f])
    fila_nuevaz.append(operacion)
print(fila_nuevaz)    

[ 1 -1 -3  0  0  0  0]
[-3, -3, -3, -3, -3, -3, -3]
[1.0, -4.0, 3.0, 0.0, 3.0, 0.0, 36.0]


- Ahora ordenemos de nuevo las tablas

<br>

##### Tabla Simplex #2
| Variables Basicas | Z | $$X_1$$ | $$X_2$$ | $$S_1$$| $$S_2$$ | $$S_3$$ | C.R
| --- | --- | --- | --- | --- | --- | --- | --- |
| $$S_1$$  | 0 | 2 | 0 | 1 | -1/4 |  0 | 15
| $$X_2$$  | 0 | 1 | 1 | 0 | 1/8 | 0  | 5/2
| $$S_3$$  | 0 | -2 | 0 | 0 | -1/4 | 1  | 5
| $$Z$$    | 1 | 10 | 0 | 0 | 5/2 | 0 | 50


In [16]:
#Aqui pueden reajustarlas con reshape
print(fila_nuevaS1)    
print(FE)
print(fila_nuevaS3) 
print(fila_nuevaz) 

[0.0, 0.0, -1.0, 1.0, -1.0, 0.0, -8.0]
[0.0, -1.0, 2.0, 0.0, 1.0, 0.0, 12.0]
[0.0, 2.0, -1.0, 0.0, -1.0, 1.0, -2.0]
[1.0, -4.0, 3.0, 0.0, 3.0, 0.0, 36.0]


Corroboramos que ya no existan valores negativos en $Z$

In [17]:
contador = 0
for w in fila_nuevaz:
    
    if(w<0):
        print("Puede optimizarse más")
        contador = 1
    else: 
        contador = 0
if(contador == 0):
    print("Encontramos la opcion optima")

Puede optimizarse más
Encontramos la opcion optima


Se tiene que hacer otra iteracion más

0.0

In [27]:
FE2 = []
for v in range(len(fila_nuevaS1)):
    division = fila_nuevaS1[v] / 2
    print(division)
    FE2.append(division)
print(FE2)

0.0
0.0
-0.5
0.5
-0.5
0.0
-4.0
[0.0, 0.0, -0.5, 0.5, -0.5, 0.0, -4.0]


Los valores finales seran los C.R que encontramos en la funcion $X_2$ y en la funcion $Z$ 

In [18]:
print(FE[-1:])
print(fila_nuevaz[-1:])

[12.0]
[36.0]


Reemplazando en la funcion original tenemos que:

 <br>
 
 $X_2$ <-  $5/2$ 
 $Z$   <-   50    
 
 <br>
 
 $Z = 10 X_1 + 20X_2$
 
 <br>
 
 $50 = 10(0) + 20(5/2)$
 
 $50=50$

#### Listo! 
Ya tenemos nuestra solución