# Breve introduccion al lenguaje  Python.

Python es un lenguaje de programación no tipado potente y fácil de aprender. Tiene estructuras de datos de alto nivel eficientes y un simple pero efectivo sistema de programación orientado a objetos. La elegante sintaxis de Python y su tipado dinámico, junto a su naturaleza interpretada lo convierten en un lenguaje ideal para scripting y desarrollo rápido de aplicaciones en muchas áreas, para la mayoría de plataformas.

Este tutorial introduce al lector informalmente a los conceptos básicos y las funcionalidades del lenguaje de programación Python y a su sistema. Ayuda a tener un interprete de Python accesible para una experiencia práctica, todos los ejemplos son auto-contenidos, permitiendo utilizar el tutorial sin conexión.

# Tipos de datos

In [1]:
x1= 5   #Entero
x2= 5.6 #Flotante
x3= "Hola mundo"# Caracter (string)
x4= True # Logico

type(x1)

int

# Indicaciones basicas

In [2]:
import math  # Con el comando (palabra reservada) import podemos cargar las bibliotecas que querramos utilizar
import numpy
import pandas
import matplotlib

In [3]:
from math import pi # Tambien podemos accesar solo algunos metodos o constantes especificos de una bibloteca

In [4]:
from math import * # De esta forma accesamos a todos los componentes incluidos en una biblioteca dada

In [5]:
math.pi# Cargamos algunas constantes especificas
print(math.pi)
math.e 

3.141592653589793


2.718281828459045

In [6]:
math.nan

nan

In [7]:
math.inf   # Formas de cargar los numeros infinito y mas infinito
-math.inf
float(inf)

inf

Tambien podemos invocar algunas funciones pre-programadas.

In [8]:
math.sqrt(-34.8)


ValueError: math domain error

In [9]:
math.log(21.32)

3.0596455992976437

In [10]:
math.exp(1000)

OverflowError: math range error

In [11]:
math.pow(math.nan,0)

1.0

In [12]:
math.sqrt(-1.0)

ValueError: math domain error

# Representacion numerica.

In [13]:
2+2 # Suma

4

In [14]:
2-3 # Resta

-1

In [15]:
3*4 # Multiplicacion

12

In [16]:
4/5.6 # Division

0.7142857142857143

In [17]:
math.floor(3.4) # Redondeo a la baja

3

In [18]:
math.ceil(5.6) # Redondeo a la alza

6

In [19]:
math.copysign(-3,-54.4)

-3.0

In [20]:
math.fabs(-6.7)

6.7

In [21]:
2.6**3.4

25.75783655629277

In [22]:
math.factorial(4)

24

In [23]:
4/3

1.3333333333333333

In [24]:
7//3
math.fmod(4,3)

1.0

In [25]:
4%3
math.remainder(4,3)

1.0

In [26]:
math.modf(4.5)

(0.5, 4.0)

In [27]:
math.gcd(66,45)

3

In [28]:
math.isfinite(4.5)

True

In [29]:
math.isinf(5.6)

False

In [30]:
math.isnan(5.78)

False

# Comandos de entrada y salida de datos.

In [31]:
print("Hola mundo.")

Hola mundo.


In [32]:
x= 7878.23

print(x)

7878.23


In [33]:
x1=float(5)

In [34]:
print("El valor de la variable ingresada es;",x)

El valor de la variable ingresada es; 7878.23


In [35]:
print("EL valor de la variable ingresada es "+str(x))

EL valor de la variable ingresada es 7878.23


Usamos el comando input para introducir informacion desde pantalla.

In [47]:
texto= input("Escriba su nombre; ")

Escriba su nombre; Alfonso


In [48]:
type(texto)

str

In [49]:
print("Hola,"+str(texto)+"." )

Hola,Alfonso.


# Operadores de desicion (and, or, !).

if o1:

   accion1
   
elif o2:
   
   accion2

elif o3:
   
   action3
  
  .
  .
  .
  
else:    

   action 
    
    

Escriba instrucciones de codigo que identifiquen si un numero esta en el intervalo [9,19]

In [50]:
x= float(input("Ingrese un numero"))

if not(9<=x and 19>= x):
    print("El numero, "+str(x)+"  esta en el intervalo [9,19]")
    
else:
    print("El numero, "+str(x)+" no esta en el intervalo [9,19]")
    
#<=, >=, ==, !=,<>
# and, or

Ingrese un numero45
El numero, 45.0  esta en el intervalo [9,19]


In [52]:
x=7.0
if x != 5 :
    print("Su numero no es 5")
    
#elif x<5:
    
 #   print("Su numero es menor que 5")
    

Su numero no es 5


## Funciones matematicas

In [53]:
math.exp(3.4)

29.96410004739701

In [54]:
math.pow(2,3)

8.0

In [55]:
math.log(12.3)

2.509599262378372

In [56]:
math.log(8,2)

3.0

$Funciones \hspace{3mm} trigonometricas$

$\pi$ Rad = 180 Deg

In [57]:
math.sin(12.21)

-0.34887519008606005

In [58]:
math.cos(23.2323)

-0.32370707015536226

In [59]:
math.tan(324.34)

0.9427849959890139

In [60]:
math.cot(324.34)

AttributeError: module 'math' has no attribute 'cot'

In [61]:
math.sinh(23.23)

6132404857.104842

In [62]:
math.cosh(4.5)

45.014120148530026

In [63]:
math.gamma(6.8)

496.6060775736907

# Definicion de funciones.

In [64]:
def saludar():
    x= input("Escriba su nombre")
    print("Hola"+x)


In [65]:
saludar()

Escriba su nombreAlfonso
HolaAlfonso


In [67]:
def suma(a,b):
    
    r= a+b
    
    return r  

z= suma(3,4)
print(z)

7


Creemos una funcion que, dado un numero x nos indique si un numero esta en el intervalo [a,b]

Clases y programacion orientada a objetos(POO).

# Crearemos una clase, que emula el comportamieto de una tarjea de credito

In [68]:
class CreditCard:
        
    def  __init__(self,cliente,banco,cuenta,cod_seg,limit,Date_Cut):
    
   # Instancias
        self._cliente=cliente
        self._banco=banco
        self._cuenta= cuenta
        self._cod_seg=cod_seg
        self._limit=limit
        self._Data_cut=Date_Cut
        self._balance = 0
    
    # Metodos
    def get_cliente(self):
        
        return self._cliente
    
    def get_banco(self):
        
        return self._banco
    
    def get_cuenta(self):
        
        return self._cuenta
    
    def get_limit(self):
        
        return self._limit
        
    def get_balance(self):
        
        return self._balance
    
    def allow_charge(self,precio):
        
        if precio+self._balance<= self._limit:
            self._balance= precio+ self._balance
            print(" Compra aceptada")
        else:    
            print("Compra no aceptada")

In [69]:
Tarjeta1= CreditCard("Alfonso S.A.","BN",123456,123,1000,"23-08")


In [70]:
Tarjeta1.get_balance()

0

In [71]:
Tarjeta1.allow_charge(1000.0)

 Compra aceptada


# Estructuras de datos.

### Las listas de Python.

Las listas de python son contenedores que permiten almacenar una coleccion de objetos en un orden determinado. Se pueden acceder añadir o eliminar objetos de forma sencilla.

In [72]:
L1=[] # Lista vacia

In [73]:
L2=["a", "e", "i", 12, 45.6, True]

In [74]:
L2= 2*L2
L2

['a', 'e', 'i', 12, 45.6, True, 'a', 'e', 'i', 12, 45.6, True]

In [75]:
L2[1],L2[10],L2[11]


('e', 45.6, True)

In [76]:
L2[0:2]

['a', 'e']

In [77]:
L3=[3,[1,23.3],[12.34,True],["Hola", 12.34, ]]

In [78]:
L3.append("VAA") # Anadimos objetos a nuestra lista

In [79]:
L3

[3, [1, 23.3], [12.34, True], ['Hola', 12.34], 'VAA']

In [80]:
L3.append([1.2,"Char",5]) # Incluso podemos anadir otras listas

In [81]:
L3.append(3)
L3

[3, [1, 23.3], [12.34, True], ['Hola', 12.34], 'VAA', [1.2, 'Char', 5], 3]

In [82]:
L3.remove(3) # Elimina la primera ocurrencia del objeto 

In [83]:
L3

[[1, 23.3], [12.34, True], ['Hola', 12.34], 'VAA', [1.2, 'Char', 5], 3]

In [84]:
L3.append(3)

In [85]:
L3

[[1, 23.3], [12.34, True], ['Hola', 12.34], 'VAA', [1.2, 'Char', 5], 3, 3]

In [86]:
L3.count(3)

2

In [87]:
L3.reverse()

In [88]:
L3

[3, 3, [1.2, 'Char', 5], 'VAA', ['Hola', 12.34], [12.34, True], [1, 23.3]]

In [89]:
L3.index(3)


0

In [90]:
L3.index(3,0,2)# Buscamos el primer indice donde aparece el 3, en el intervalo de indice del 0 al 2

0

In [91]:
len(L3)

7

In [92]:
L=[1,2,3,4,5,6,7]

In [93]:
L

[1, 2, 3, 4, 5, 6, 7]

### Bucles y listas.

In [94]:
for numero in L:
    print(numero)

1
2
3
4
5
6
7


In [95]:
C1= input("Ingrese un conjunto de numeros separados por una coma.")
L1= C1.split(",")
L1

Ingrese un conjunto de numeros separados por una coma.1,2,3,4,5


['1', '2', '3', '4', '5']

In [96]:
l= len(L1)

for i in range(l):
    
    L1[i]=int(L1[i])

In [97]:
L1

[1, 2, 3, 4, 5]

In [98]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [99]:
for c in "Buenos dias":
    print(c)

B
u
e
n
o
s
 
d
i
a
s


### Tuplas

Una tupla es una coleccion de objetos que no puede modificarse (tiene tamano y contenido fijo).

In [100]:
T1=(1,2,3,4)
T1

(1, 2, 3, 4)

In [101]:
T2= (1,2,3,"Tupla 2",3.45,5.6)
T2

(1, 2, 3, 'Tupla 2', 3.45, 5.6)

In [102]:
T2[0]

1

In [103]:
T2[2:3],T2[3:],T2[:4]

((3,), ('Tupla 2', 3.45, 5.6), (1, 2, 3, 'Tupla 2'))

In [104]:
print(L1)
print(T1)

[1, 2, 3, 4, 5]
(1, 2, 3, 4)


In [105]:
L4=[3.4,5.6,6,"Clase"]

In [106]:
T3= tuple(L4)
T3

(3.4, 5.6, 6, 'Clase')

In [107]:
L5=list(T2)
L5

[1, 2, 3, 'Tupla 2', 3.45, 5.6]

### Diccionarios.

Tambien conocidos como arreglos asociativos, son colecciones NO ordenadas de pares de objetos (claves y valores). Se indexa no por posicion, si no utilizando claves

In [108]:
Cuenta={
        "Karl Friedrich": 123, 
        "Alan Turin":345,
        "Evarite Galois": 567 
       }

In [109]:
  print(Cuenta)

{'Karl Friedrich': 123, 'Alan Turin': 345, 'Evarite Galois': 567}


In [110]:
Cuenta["Karl Friedrich"]

123

In [111]:
Cuenta["Karl Friedrich"]= 000

In [112]:
Cuenta["Karl Friedrich"]

0

In [113]:
Cuenta.keys()

dict_keys(['Karl Friedrich', 'Alan Turin', 'Evarite Galois'])

In [114]:
Cuenta.values()

dict_values([0, 345, 567])

In [115]:
len(Cuenta)

3

In [116]:
"Einstein" in Cuenta

False

### Arreglos de NumPy

Los arreglos de NumPy son estructuras de datos que contienen datos de un mismo tipo.

In [118]:
import numpy as np

In [119]:
L1=[1,2,3,4,5,6,7,8,9]

In [120]:
x1= np.array(L1)

In [121]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
x2= np.ones((3,4))

In [123]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.arange(4,5.43,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4])

In [125]:
np.linspace(1,7,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [126]:
x2.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [127]:
np.resize(x2,(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Universalidad de las funciones

In [129]:
x3= np.arange(10)
x3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
x3+3.4

array([ 3.4,  4.4,  5.4,  6.4,  7.4,  8.4,  9.4, 10.4, 11.4, 12.4])

In [131]:
x3-3.1415
3.1415*x3
x3/3.1415

array([0.        , 0.31831927, 0.63663855, 0.95495782, 1.2732771 ,
       1.59159637, 1.90991565, 2.22823492, 2.54655419, 2.86487347])

In [152]:
x4= np.linspace(0,2*np.pi,4)

In [153]:
x5= np.arange(12) 
x5= np.resize(x5,(5,3))

In [154]:
np.sin(x4)
np.cos(x4)
np.exp(x4)
np.power(3,x4)
np.mean(x4)
np.median(x4)
np.min(x4)
np.std(x4)
np.var(x4)
np.argmin(x4)
np.argmax(x4)
x5.sum()
x5.sum(axis=0)
x5.sum(axis=1)

array([ 3, 12, 21, 30,  3])

### Modulo de algebra lineal

In [146]:
A= np.arange(12) 
A= np.resize(A,(5,3))
B= np.arange(12)
B= np.resize(B,(3,5))
B= 5+B
C= np.arange(16)
C= np.resize(C,(4,4))

In [147]:
np.dot(A,B)

array([[ 40,  43,  22,  25,  28],
       [130, 142,  94, 106, 118],
       [220, 241, 166, 187, 208],
       [310, 340, 238, 268, 298],
       [ 40,  43,  22,  25,  28]])

In [148]:
np.transpose(A)
np.trace(A)
np.linalg.matrix_power(C,5)
np.linalg.det(C)
#np.linalg.inv(C)

0.0